version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/

hooks:
  BeforeInstall:
    - location: scripts/docker_login.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/docker_container.sh
      timeout: 300
      runas: ubuntu
#    - location: scripts/docker_container&start1.sh
#      timeout: 300
#      runas: root

  ValidateService:
    - location: scripts/validate.sh
      timeout: 300
      runas: ubuntu